### ISSUE TITLE
Misspelling in nav tree for "High availability and resiliency for infrastructure"

### ISSUE THREAD

**Issue by aerwin** [ibm-cloud-docs/ha-infrastructure#1]
The nav pane for this collection has a "applictions" misspelled (missing an "a"):

<img width="294" alt="image" src="https://github.com/ibm-cloud-docs/ha-infrastructure/assets/1258743/21b1021d-a687-4ed8-b962-d36897068d4d">

**Comment by addison-martin1** [comment]
Thank you for your valued feedback. This repository is being deprecated.
